import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/ui/globals.css"
// import { Providers } from "../components/providers";
// import "@repo/ui/styles/"
import { cn } from "@repo/ui/lib/utils";
import { Providers } from "@/components/providers";
// Or create the file at src/components/providers.tsx if it doesn't exist.

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
