import type { Metadata } from "next";
import { AppSidebar } from "@/components/app-sidebar";
import { SiteHeader } from "@/components/site-header";
import { SidebarInset, SidebarProvider } from "@repo/ui/components/sidebar";
// import { ScrollArea } from "@repo/ui/components/scroll-area";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <SidebarProvider
      style={
        {
          "--header-height": "calc(var(--spacing) * 12)",
        } as React.CSSProperties
      }
      >
        <AppSidebar variant="inset" />
        <SidebarInset>
          <SiteHeader />
          {/* <ScrollArea
            className="max-h-[calc(100vh-var(--header-height))] overflow-y-auto w-full flex flex-1 flex-col"
          > */}
            {children}
          {/* </ScrollArea> */}
        </SidebarInset>
      </SidebarProvider>
  );
}
