import React from 'react'

const page = () => {
  return (
    <div className='font-bold text-4xl text-center text-red-500'>
      hey broo
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed reiciendis ullam assumenda quo hic architecto molestias ipsum totam fugiat, quam aspernatur sit, doloremque accusantium esse illum distinctio quis ab, dignissimos corrupti quidem laborum eius? Veritatis in eveniet neque a. Natus consequatur eum nesciunt quisquam libero facilis itaque nisi sapiente ex mollitia officia id reiciendis enim praesentium cumque obcaecati ullam aspernatur quibusdam molestiae ea illo, aliquam explicabo corrupti sed? In aut atque aspernatur? Perferendis mollitia ab assumenda minima possimus, ipsa nemo provident, reprehenderit tenetur magnam veritatis reiciendis omnis impedit necessitatibus excepturi quasi nostrum nesciunt consequatur voluptatibus explicabo? Molestiae accusamus omnis, aliquid excepturi aspernatur optio nisi libero. Vero aliquid esse alias asperiores cupiditate nisi dolores reprehenderit repudiandae ipsum animi consequuntur delectus fugiat earum saepe dolor veritatis dolorum eligendi reiciendis vel corporis, iure, quasi ipsa quod explicabo. Saepe similique officiis quasi necessitatibus ut dolor, dignissimos, voluptatibus recusandae molestias dolorum beatae non, eligendi quaerat doloribus veniam animi aut in iste. Autem quam quisquam nemo dolor rem! Veritatis id non itaque eum repellat reprehenderit labore numquam excepturi commodi doloremque harum dolorum expedita distinctio, animi atque fugit accusantium laborum deserunt quasi modi saepe suscipit? Expedita quod, deleniti libero perferendis voluptates nihil perspiciatis? Reprehenderit cupiditate perspiciatis quis provident nam exercitationem maxime! Sit corporis doloribus laborum at ipsa accusantium velit quos ratione, repudiandae delectus officiis harum odit laudantium qui tenetur odio totam voluptates earum corrupti. Quidem accusamus nostrum eaque recusandae ducimus officia voluptatum cumque quas adipisci suscipit. Itaque eos nihil qui quia minus nemo maxime voluptatem magni, sunt voluptate, ullam quae aliquam fugiat dignissimos quaerat harum cupiditate modi natus sint unde! Provident accusantium perferendis voluptate asperiores, quam tenetur pariatur. Quia aliquam alias voluptate, minus reiciendis, unde aspernatur doloremque, eveniet ratione facere ea iusto quisquam ipsa id porro nesciunt? Esse laboriosam eveniet cumque, consequatur rem commodi. Mollitia fugit nam culpa error. Et omnis earum, pariatur placeat expedita quisquam quas neque rerum voluptas. Saepe, architecto adipisci voluptatibus natus numquam sequi tenetur quia repellendus, reiciendis, dolorem aliquam hic non? Ex at doloribus accusantium, error consequatur dicta, ab possimus est ullam architecto molestiae ratione sint nemo rerum.
    </div>
  )
}

export default page
